name: chatmates_flutter
description: A new Flutter chat app project.
publish_to: 'none' # Remove this line to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  stomp_dart_client: ^0.4.4
  web_socket_channel: ^2.4.0
  http: ^0.13.6
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
